In [1]:
import pandas as pd

# 첫번째 의뢰작업

In [44]:
df = pd.read_excel('../data/기호식품 원재료명 정리_1차.xlsx')
df

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),...,112,113,114,115,116,117,118,119,120,121
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,196306060011,생강맛전병,과자(기타),57750.0,137500.0,57750.0,195250.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,1966040200386,허쉬 초콜릿 칩 쿠키,과자(쿠키),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,196704780087,우리밀땅콩셈비,과자(기타),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,1968012801689,수제땅콩전병,과자(쿠키),0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681,2021,202100841053,두부로운 히말라얀핑크솔트맛,과자(스낵과자류),1000.0,1160.0,1000.0,3000.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3682,2021,202103351281,순수현미,과자(기타),380.0,4000.0,360.0,6000.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3683,2021,202103351284,순수현미단호박,과자(기타),250.0,3000.0,240.0,4000.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3684,2021,202103351283,순수현미양파,과자(기타),250.0,3000.0,240.0,4000.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3685,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df.iloc[:, 0:15].head()

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),국외판매금액(천원),품목유형_중,N_원재료,1,2
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,밀가루(45),설탕(50)
1,2021,196306060011,생강맛전병,과자(기타),57750.0,137500.0,57750.0,195250.0,0.0,0.0,0.0,과자,8,밀가루(44),설탕(48)
2,2021,1966040200386,허쉬 초콜릿 칩 쿠키,과자(쿠키),0.0,0.0,0.0,0.0,0.0,0.0,0.0,과자,11,백설탕(19.8),베이킹파우더(0.385)
3,2021,196704780087,우리밀땅콩셈비,과자(기타),0.0,0.0,0.0,0.0,0.0,0.0,0.0,과자,6,밀가루(25),설탕(25)
4,2021,1968012801689,수제땅콩전병,과자(쿠키),0.0,0.0,0.0,0.0,0.0,0.0,0.0,과자,17,밀가루(60),계란(15)

In [48]:
data = df.head(1)
data

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),...,112,113,114,115,116,117,118,119,120,121
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
data.iloc[:, 0:15].head()

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),국외판매금액(천원),품목유형_중,N_원재료,1,2
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,밀가루(45),설탕(50)

In [52]:
data.columns[0:13]

Index(['보고년도', '품목보고번호', '제품명', '품목유형(생산실적)', '생산량(KG)', '생산액(천원)',
       '국내판매량(KG)', '국내판매금액(천원)', '국외판매량(KG)', '국외판매금액($)', '국외판매금액(천원)',
       '품목유형_중', 'N_원재료'],
      dtype='object')

In [53]:
tf = data.melt(id_vars= data.columns[0:13], var_name="순서", value_name="원재료").dropna()
tf

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),국외판매금액(천원),품목유형_중,N_원재료,순서,원재료
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,1,밀가루(45)
1,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,2,설탕(50)
2,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,3,마가린(1)
3,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,4,생강(1)
4,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,5,검정깨(흑임자)(2.99)
5,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,6,중탄산암모늄(팽창제)(0.01)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from tqdm import tqdm

for i in tqdm(range(1, len(df))) : #range(len(df)):
    tf = tf.append(df[(i+0):(i+1)].melt(id_vars= data.columns[0:13], var_name="순서", value_name="원재료").dropna())

In [ ]:
tf.to_excel('../data/기호식품 원재료명 정리_1차_logntype.xlsx')

# 두번째 의뢰작업

In [54]:
#file ='20220926_20220922_영양기능연구과_안정선_과자  빵류  초콜릿류  시리얼류_생산실적_하위원재료표시_2차 원재료명 작업.xlsx'
#df = pd.read_excel('../data/' + file)

In [55]:
#df.to_pickle('../pkl/2차자료.pickle')
df = pd.read_pickle('../pkl/2차자료.pickle')
df

,인허가번호,보고년도,인허가일자,품목제조보고일,업체명(생산실적),대표자명(생산실적),업종,품목대장전산키,품목보고번호,품목보고번호_01,...,61,62,63,64,65,66,67,68,69,70
0,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19690086003,2021,19690307,20210707.0,롯데제과(주),이영구,식품제조가공업,2.021021e+15,196900860031339,196900860031339,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19690086003,2021,19690307,20201012.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031167,196900860031167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19730347003,2021,19731015,20170517.0,로얄제과(주),나기준,식품제조가공업,2.017021e+15,197303470031063,197303470031063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19730347003,2021,19731015,20170627.0,로얄제과(주),나기준,식품제조가공업,2.017021e+15,197303470031076,197303470031076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1534,20160080733,2021,20160722,20200427.0,(주)카카오브라운,정영택,식품제조가공업,2.020021e+15,20160080733382,20160080733382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1535,20160080733,2021,20160722,20191205.0,(주)카카오브라운,정영택,식품제조가공업,2.019021e+15,20160080733368,20160080733368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1536,20160080733,2021,20160722,20211209.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733575,20160080733575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537,20160080733,2021,20160722,20190401.0,(주)카카오브라운,정영택,식품제조가공업,2.019021e+15,20160080733342,20160080733342,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1538,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 3. 첫 줄을 변화하여 보기
- df.head(1) : 1번쨰 데이터만 보여라, 이것을 data에 저장하라는 의미
- 13번째 가지 컬럼은 유지하고 나머지는 녹여서 아래로 붙여라
### 한글명 컬럼이 있는 순번은 어디인지 확인

In [56]:
df.iloc[:, 0:15].head(2)

,인허가번호,보고년도,인허가일자,품목제조보고일,업체명(생산실적),대표자명(생산실적),업종,품목대장전산키,품목보고번호,품목보고번호_01,품목유형(생산실적),제품명,생산량(KG),생산액(천원),국내판매량(KG)
0,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,과자(비스킷류),그릴드 베지 빼빼로,0.0,0.000,0.0
1,19690086003,2021,19690307,20210707.0,롯데제과(주),이영구,식품제조가공업,2.021021e+15,196900860031339,196900860031339,과자(기타),ABC초코쿠키 민트초코,114521.0,1087551.848,65744.0

In [57]:
df.iloc[:, 15:35].head()

,국내판매금액(천원),국외판매량(KG),국외판매금액(천원),원재료1레벨,품목_중,영양성분 code 유무,영양성분 code,원재료 작업 여부,원재료1레벨.1,N_원재료명,1,2,3,4,5,6,7,8,9,10
0,0.000,0.0,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,NaN,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.9485),가공연유(3.1885),곡류가공품(2.3618),가공버터(1.7714),기타가공품(1.0628),물엿(0.8562),정제소금(0.6495)
1,1087551.848,0.0,0.0,"식물성크림(52.9139)[설탕,기타가공품,가공유지,덱스트린,유청단백분말],과자(4...",과자,Y,P103-006020100-0017,NaN,"식물성크림(52.9139)[설탕,기타가공품,가공유지,덱스트린,유청단백분말],과자(4...",18,식물성크림(52.9139)[설탕,기타가공품,가공유지,덱스트린,유청단백분말],과자(45.8333)[쇼트닝,코코아분말,설탕,전란액,밀가루]
2,0.000,0.0,0.0,"밀가루(49.18),백설탕(25.57),쇼트닝(14.95),코코아분말(6.29),옥...",과자,Y,P103-006020100-0017,NaN,"밀가루(49.18),백설탕(25.57),쇼트닝(14.95),코코아분말(6.29),옥...",10,밀가루(49.18),백설탕(25.57),쇼트닝(14.95),코코아분말(6.29),옥수수전분(1.48),과당(1.18),전지분유(0.73),레시틴(0.16),바닐라향(0.03),정제소금(0.43)
3,0.000,0.0,0.0,"아몬드분말(30.3),백설탕(30.3),난백액(21.2),마가린(9.1),박력분(4...",과자,Y,P103-006020200-0007,NaN,"아몬드분말(30.3),백설탕(30.3),난백액(21.2),마가린(9.1),박력분(4...",6,아몬드분말(30.3),백설탕(30.3),난백액(21.2),마가린(9.1),박력분(4.55),정제수(4.55),NaN,NaN,NaN,NaN
4,0.000,0.0,0.0,"백설탕(30.537),아몬드분말(27.27),난백액(19.08),마가린(8.19),...",과자,Y,P103-006020200-0007,NaN,"백설탕(30.537),아몬드분말(27.27),난백액(19.08),마가린(8.19),...",18,백설탕(30.537),아몬드분말(27.27),난백액(19.08),마가린(8.19),박력분(4.095),정제수(4.095),코코아분말(2.797),코코아버터(1.361),코코아매스(1.114),식물성경화유(0.99)

##  ['원재료 작업 여부']컬럼에 NANㅇ 있기때문에 melt 명령어에서 dropna()하면 모두 사라지니 fillna('missing')하고 진행

In [63]:
data[data.columns[0:25]].isnull().sum()

인허가번호           0
보고년도            0
인허가일자           0
품목제조보고일         0
업체명(생산실적)       0
대표자명(생산실적)      0
업종              0
품목대장전산키         0
품목보고번호          0
품목보고번호_01       0
품목유형(생산실적)      0
제품명             0
생산량(KG)         0
생산액(천원)         0
국내판매량(KG)       0
국내판매금액(천원)      0
국외판매량(KG)       0
국외판매금액(천원)      0
원재료1레벨          0
품목_중            0
영양성분 code 유무    0
영양성분 code       0
원재료 작업 여부       1
원재료1레벨.1        0
N_원재료명          0
dtype: int64

In [69]:
df['원재료 작업 여부'] = df['원재료 작업 여부'].fillna('missing')

In [70]:
data = df.head(1)
data

,인허가번호,보고년도,인허가일자,품목제조보고일,업체명(생산실적),대표자명(생산실적),업종,품목대장전산키,품목보고번호,품목보고번호_01,...,61,62,63,64,65,66,67,68,69,70
0,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
tf = data.melt(id_vars= data.columns[0:25], var_name="순서", value_name="원재료").dropna()
tf

,인허가번호,보고년도,인허가일자,품목제조보고일,업체명(생산실적),대표자명(생산실적),업종,품목대장전산키,품목보고번호,품목보고번호_01,...,국외판매금액(천원),원재료1레벨,품목_중,영양성분 code 유무,영양성분 code,원재료 작업 여부,원재료1레벨.1,N_원재료명,순서,원재료
0,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,1,밀가루(70.8568)
1,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,2,설탕(8.8569)
2,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,3,과채가공품(5.9046)
3,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,4,쇼트닝(1.9485)
4,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,5,가공연유(3.1885)
5,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,6,곡류가공품(2.3618)
6,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,7,가공버터(1.7714)
7,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,8,기타가공품(1.0628)
8,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,9,물엿(0.8562)
9,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,10,정제소금(0.6495)
10,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,11,곡류가공품(0.5905)
11,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,12,액상과당(0.5314)
12,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,13,복합조미식품(0.4133)
13,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,14,합성향료(0.1476)
14,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,15,합성향료(0.1299)
15,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,16,탄산수소나트륨(0.0866)
16,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,17,프로테아제(0.0443)
17,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,18,효모(0.0089)
18,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,19,제삼인산나트륨(0.5905)

In [74]:
import warnings
warnings.filterwarnings('ignore')
from tqdm import tqdm

for i in tqdm(range(1, len(df))) : #range(len(df)):
    tf = tf.append(df[(i+0):(i+1)].melt(id_vars= data.columns[0:25], var_name="순서", value_name="원재료").dropna())

100%|██████████████████████████████████████████████████████████████████████████████| 1538/1538 [00:29<00:00, 52.74it/s]

In [76]:
tf.to_excel('../data/기호식품 원재료명 정리_2차_logntype.xlsx')

In [75]:
tf

,인허가번호,보고년도,인허가일자,품목제조보고일,업체명(생산실적),대표자명(생산실적),업종,품목대장전산키,품목보고번호,품목보고번호_01,...,국외판매금액(천원),원재료1레벨,품목_중,영양성분 code 유무,영양성분 code,원재료 작업 여부,원재료1레벨.1,N_원재료명,순서,원재료
0,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,1,밀가루(70.8568)
1,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,2,설탕(8.8569)
2,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,3,과채가공품(5.9046)
3,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,4,쇼트닝(1.9485)
4,19690086003,2021,19690307,20200114.0,롯데제과(주),이영구,식품제조가공업,2.020021e+15,196900860031818,196900860031818,...,0.0,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",과자,Y,P103-006020100-0017,missing,"밀가루(70.8568),설탕(8.8569),과채가공품(5.9046),쇼트닝(1.94...",19,5,가공연유(3.1885)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,0.0,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",빵류,Y,P103-006020100-0177,missing,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",9,5,콩기름(대두유)(6.674)[세부원재료
5,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,0.0,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",빵류,Y,P103-006020100-0177,missing,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",9,6,규소수지]
6,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,0.0,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",빵류,Y,P103-006020100-0177,missing,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",9,7,식품첨가물혼합제제(1.526)
7,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,0.0,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",빵류,Y,P103-006020100-0177,missing,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",9,8,합성팽창제(0.191)
8,20160080733,2021,20160722,20210114.0,(주)카카오브라운,정영택,식품제조가공업,2.021021e+15,20160080733504,20160080733504,...,0.0,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",빵류,Y,P103-006020100-0177,missing,"전란액(38.139),설탕(22.883),밀가루(22.883),우유(7.628),콩...",9,9,가공소금(0.076)

In [39]:
tf

,보고년도,품목보고번호,제품명,품목유형(생산실적),생산량(KG),생산액(천원),국내판매량(KG),국내판매금액(천원),국외판매량(KG),국외판매금액($),국외판매금액(천원),품목유형_중,N_원재료,순서,원재료
0,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,1,밀가루(45)
1,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,2,설탕(50)
2,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,3,마가린(1)
3,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,4,생강(1)
4,2021,196306060015,깨맛전병,과자(기타),9750.0,17500.0,9750.0,27250.0,0.0,0.0,0.0,과자,6,5,검정깨(흑임자)(2.99)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,0.0,과자,6,2,기타가공품(30)
2,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,0.0,과자,6,3,쌀
3,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,0.0,과자,6,4,울금덩이뿌리분말
4,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,0.0,과자,6,5,효소처리스테비아(0.1)
5,2021,202103351282,순수현미울금,과자(기타),120.0,1800.0,108.0,2500.0,0.0,0.0,0.0,과자,6,6,재제소금(재제조소금)(0.1)

In [48]:
tf.shape

(114232, 15)

In [ ]:
# End